# Generated by Django 2.2 on 2021-08-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210810_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_condition',
            field=models.IntegerField(choices=[(1, '새제품'), (2, '최상'), (3, '상'), (4, '중'), (5, '하')]),
        ),
    ]
